STRINGS = {
    "tr": {
        "select_lang": "Dil Secin",
        "main_menu": "ANA MENU",
        "osint": "OSINT Araclari",
        "network": "Ag Araclari",
        "hashing": "Hash Araclari",
        "encoding": "Kodlama Araclari",
        "ciphers": "Sifreleme (Cipher)",
        "password": "Parola Araclari",
        "exit": "Cikis",
        "back": "Geri Don",
        "nav_hint": "YON TUSLARI: Gezin | ENTER: Sec | Q: Geri/Cikis",
        "enter_target": "Hedef (domain / IP)",
        "enter_text": "Metin",
        "enter_key": "Anahtar",
        "enter_port": "Port",
        "enter_port_range": "Port araligi (orn 1-1000)",
        "enter_length": "Uzunluk",
        "enter_shift": "Kaydirma degeri (1-25)",
        "enter_rails": "Ray sayisi (2+)",
        "enter_salt": "Salt (bos birakilabilir)",
        "enter_subnet": "Subnet (orn 192.168.1)",
        "enter_username": "Kullanici adi",
        "enter_domain": "Domain",
        "enter_email": "Email adresi",
        "enter_phone": "Telefon (orn +905551234567)",
        "enter_mac": "MAC adresi (orn AA:BB:CC:DD:EE:FF)",
        "enter_words": "Kelimeler (virgul ile ayirin)",
        "enter_password": "Parola",
        "enter_word_count": "Kelime sayisi (3-12)",
        "enter_url": "URL",
        "enter_jwt": "JWT token",
        "type_hint": "Yazin, ENTER'a basin",
        "press_enter": "ENTER veya Q ile devam",
        "invalid_choice": "Gecersiz secim",
        "weak": "ZAYIF", "medium": "ORTA", "strong": "GUCLU", "very_strong": "COK GUCLU",
        "username_search": "Kullanici Adi Arama (30+ site)",
        "social_link_gen": "Sosyal Medya Link Uretici",
        "whois_lookup": "Whois Sorgulama",
        "domain_age": "Domain Yas Tespiti",
        "dns_lookup": "DNS Sorgulama",
        "ip_lookup": "IP Bilgi Sorgulama",
        "email_lookup": "Email Format Analizi",
        "phone_analysis": "Telefon Numarasi Analizi",
        "google_dork": "Google Dork Uretici",
        "port_scan": "Port Tarama (aralik)",
        "top_ports": "Yaygin 20 Port Taramasi",
        "tcp_test": "Tek Port TCP Testi",
        "ping_host": "Ping Gonder",
        "ping_sweep": "Ping Taramasi (subnet)",
        "host_info": "Host / Ters DNS Bilgisi",
        "traceroute": "Traceroute",
        "http_headers": "HTTP Header Analizi",
        "ssl_info": "SSL Sertifika Bilgisi",
        "banner_grab": "Banner Yakalama",
        "subdomain_enum": "Alt Alan Adi Tarama",
        "mac_vendor": "MAC Vendor Sorgulama",
        "local_net": "Yerel Ag Bilgisi",
        "md5": "MD5 Hash", "sha1": "SHA1 Hash", "sha224": "SHA224 Hash",
        "sha256": "SHA256 Hash", "sha384": "SHA384 Hash", "sha512": "SHA512 Hash",
        "sha3_256": "SHA3-256 Hash", "sha3_512": "SHA3-512 Hash",
        "blake2b": "BLAKE2b Hash", "blake2s": "BLAKE2s Hash",
        "crc32": "CRC32 Checksum", "adler32": "Adler32 Checksum",
        "hmac256": "HMAC-SHA256", "pbkdf2": "PBKDF2 Turetme",
        "salted": "Salted SHA256", "hash_all": "Tum Hashleri Uret",
        "b64_encode": "Base64 Kodla", "b64_decode": "Base64 Coz",
        "b32_encode": "Base32 Kodla", "b32_decode": "Base32 Coz",
        "b85_encode": "Base85 Kodla", "b85_decode": "Base85 Coz",
        "b58_encode": "Base58 Kodla", "b58_decode": "Base58 Coz",
        "hex_encode": "Hex Kodla", "hex_decode": "Hex Coz",
        "bin_encode": "Binary Kodla", "bin_decode": "Binary Coz",
        "url_encode": "URL Kodla", "url_decode": "URL Coz",
        "html_encode": "HTML Entity Kodla", "html_decode": "HTML Entity Coz",
        "uni_encode": "Unicode Escape Kodla", "uni_decode": "Unicode Escape Coz",
        "puny_encode": "Punycode Kodla", "puny_decode": "Punycode Coz",
        "uuid_gen": "UUID Uret", "token_gen": "Rastgele Token Uret",
        "token_urlsafe": "URL-Safe Token Uret", "jwt_decode": "JWT Coz (verify yok)",
        "caesar": "Sezar Sifresi", "caesar_brute": "Sezar Bruteforce",
        "vigenere_enc": "Vigenere Sifrele", "vigenere_dec": "Vigenere Coz",
        "atbash": "Atbash Sifresi",
        "railfence_enc": "Rail Fence Sifrele", "railfence_dec": "Rail Fence Coz",
        "xor_enc": "XOR Sifrele", "xor_dec": "XOR Coz",
        "rot13": "ROT13", "rot47": "ROT47",
        "morse_enc": "Morse Kodla", "morse_dec": "Morse Coz",
        "nato": "NATO Fonetik", "leet": "Leet Speak", "reverse": "Metni Ters Cevir",
        "pass_check": "Parola Guc Analizi",
        "pass_common": "Yaygin Parola Kontrolu",
        "pass_entropy": "Parola Entropi Hesabi",
        "pass_gen": "Parola Uretici",
        "pass_phrase": "Passphrase Uretici",
        "pass_pin": "PIN Uretici",
        "pass_wordlist": "Wordlist Uretici",
    },
    "en": {
        "select_lang": "Select Language",
        "main_menu": "MAIN MENU",
        "osint": "OSINT Tools",
        "network": "Network Tools",
        "hashing": "Hashing Tools",
        "encoding": "Encoding Tools",
        "ciphers": "Ciphers",
        "password": "Password Tools",
        "exit": "Exit",
        "back": "Back",
        "nav_hint": "ARROWS: Navigate | ENTER: Select | Q: Back/Quit",
        "enter_target": "Target (domain / IP)",
        "enter_text": "Text",
        "enter_key": "Key",
        "enter_port": "Port",
        "enter_port_range": "Port range (e.g. 1-1000)",
        "enter_length": "Length",
        "enter_shift": "Shift value (1-25)",
        "enter_rails": "Rail count (2+)",
        "enter_salt": "Salt (leave empty for default)",
        "enter_subnet": "Subnet (e.g. 192.168.1)",
        "enter_username": "Username",
        "enter_domain": "Domain",
        "enter_email": "Email address",
        "enter_phone": "Phone (e.g. +14155551234)",
        "enter_mac": "MAC address (e.g. AA:BB:CC:DD:EE:FF)",
        "enter_words": "Words (comma separated)",
        "enter_password": "Password",
        "enter_word_count": "Word count (3-12)",
        "enter_url": "URL",
        "enter_jwt": "JWT token",
        "type_hint": "Type and press ENTER",
        "press_enter": "ENTER or Q to continue",
        "invalid_choice": "Invalid choice",
        "weak": "WEAK", "medium": "MEDIUM", "strong": "STRONG", "very_strong": "VERY STRONG",
        "username_search": "Username Search (30+ sites)",
        "social_link_gen": "Social Media Link Generator",
        "whois_lookup": "Whois Lookup",
        "domain_age": "Domain Age Estimator",
        "dns_lookup": "DNS Lookup",
        "ip_lookup": "IP Info Lookup",
        "email_lookup": "Email Format Analysis",
        "phone_analysis": "Phone Number Analysis",
        "google_dork": "Google Dork Generator",
        "port_scan": "Port Scan (range)",
        "top_ports": "Top 20 Ports Scan",
        "tcp_test": "Single Port TCP Test",
        "ping_host": "Ping Host",
        "ping_sweep": "Ping Sweep (subnet)",
        "host_info": "Host / Reverse DNS Info",
        "traceroute": "Traceroute",
        "http_headers": "HTTP Header Analysis",
        "ssl_info": "SSL Certificate Info",
        "banner_grab": "Banner Grabber",
        "subdomain_enum": "Subdomain Enumeration",
        "mac_vendor": "MAC Vendor Lookup",
        "local_net": "Local Network Info",
        "md5": "MD5 Hash", "sha1": "SHA1 Hash", "sha224": "SHA224 Hash",
        "sha256": "SHA256 Hash", "sha384": "SHA384 Hash", "sha512": "SHA512 Hash",
        "sha3_256": "SHA3-256 Hash", "sha3_512": "SHA3-512 Hash",
        "blake2b": "BLAKE2b Hash", "blake2s": "BLAKE2s Hash",
        "crc32": "CRC32 Checksum", "adler32": "Adler32 Checksum",
        "hmac256": "HMAC-SHA256", "pbkdf2": "PBKDF2 Derivation",
        "salted": "Salted SHA256", "hash_all": "Generate All Hashes",
        "b64_encode": "Base64 Encode", "b64_decode": "Base64 Decode",
        "b32_encode": "Base32 Encode", "b32_decode": "Base32 Decode",
        "b85_encode": "Base85 Encode", "b85_decode": "Base85 Decode",
        "b58_encode": "Base58 Encode", "b58_decode": "Base58 Decode",
        "hex_encode": "Hex Encode", "hex_decode": "Hex Decode",
        "bin_encode": "Binary Encode", "bin_decode": "Binary Decode",
        "url_encode": "URL Encode", "url_decode": "URL Decode",
        "html_encode": "HTML Entity Encode", "html_decode": "HTML Entity Decode",
        "uni_encode": "Unicode Escape Encode", "uni_decode": "Unicode Escape Decode",
        "puny_encode": "Punycode Encode", "puny_decode": "Punycode Decode",
        "uuid_gen": "Generate UUID", "token_gen": "Generate Random Token",
        "token_urlsafe": "Generate URL-Safe Token", "jwt_decode": "Decode JWT (no verify)",
        "caesar": "Caesar Cipher", "caesar_brute": "Caesar Bruteforce",
        "vigenere_enc": "Vigenere Encrypt", "vigenere_dec": "Vigenere Decrypt",
        "atbash": "Atbash Cipher",
        "railfence_enc": "Rail Fence Encrypt", "railfence_dec": "Rail Fence Decrypt",
        "xor_enc": "XOR Encrypt", "xor_dec": "XOR Decrypt",
        "rot13": "ROT13", "rot47": "ROT47",
        "morse_enc": "Morse Encode", "morse_dec": "Morse Decode",
        "nato": "NATO Phonetic", "leet": "Leet Speak", "reverse": "Reverse Text",
        "pass_check": "Password Strength Check",
        "pass_common": "Common Password Check",
        "pass_entropy": "Password Entropy Calculator",
        "pass_gen": "Password Generator",
        "pass_phrase": "Passphrase Generator",
        "pass_pin": "PIN Generator",
        "pass_wordlist": "Wordlist Generator",
    },
}


def t(lang, key):
    return STRINGS.get(lang, STRINGS["en"]).get(key, key)
